# Generated by Django 3.2.3 on 2021-12-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_updateprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateprofile',
            name='bloodgroup',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='updateprofile',
            name='semester',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='updateprofile',
            name='institution',
            field=models.CharField(max_length=30),
        ),
    ]
